### ISSUE TITLE
sites on blacklist not muted

### ISSUE THREAD

**Issue by Mementh** [d4rky-pl/stfu-extension#3]
so i have a bunch of twitch pages open as support and muted as default on blacklist.

had 1 unmuted that i was actively listening to.

closed chrome and re-opened and went through and control page up/down to load tabs.. all started with audio on/green. 
Keep muted state of the opening tab is off but was working, but i don't want this option on since i want if someone raids to have the new page muted.
also mute all tabs does not work!

**Comment by d4rky-pl** [comment]
@Mementh the manifest v3 continues to be a major pain in the ass. I'll investigate this sometime this week, thanks for reporting

**Comment by Mementh** [comment]
Let me know if i can send anything to help

**Comment by d4rky-pl** [comment]
@Mementh I've just pushed a new version to Chrome Web Store. Once it's released, let me know if it solved your problem

**Comment by Mementh** [comment]
> @Mementh I've just pushed a new version to Chrome Web Store. Once it's released, let me know if it solved your problem

still 2.2.0 on store so no updates yet.. will update when i can

**Comment by Mementh** [comment]
> > @Mementh I've just pushed a new version to Chrome Web Store. Once it's released, let me know if it solved your problem
> 
> still 2.2.0 on store so no updates yet.. will update when i can

manually updated to 2.3.0 and no issues.. seems to be fixed? will see if the page stays muted when a raid happens.

**Comment by d4rky-pl** [comment]
@Mementh 2.3.0 is now visible in Chrome Web Store so feel free to switch back if you installed the extension directly from this repository.

I'm going to close this issue, if you run into any further problems please don't hesitate to report them
